### ISSUE TITLE
Notifications: Controls per space

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/alkemio#1054]
## Description
Allow users to control their notifications per space and per channel type

## Initiative / goal
Tidy up the set of preferences to make it easier to understand

### Hypothesis
With a refresh it will be easier for users to understand the set of notifications/preferences, so that they can ensure they have the right set of preferences

## Acceptance criteria and must have scope
- [ ] Notifications split into user, org, platform + space settings
- [ ] Remove preferences and just use user settings
- [ ] Space notification settings to be done per space
- [ ] Users to be able to choose for each notification whether they want notification by email, in-app (if have privilege) or both
- [ ] Translation support for notifications

## Stakeholders
Users of the platform

## Design
Research: https://alkem.io/building-alkemio/challenges/mydashboardhomep-4715/opportunities/notificationsonthe-7063/dashboard

Figma file:
https://www.figma.com/file/pRGFSyng0dxovpvlaWGI8t/Notifications?type=design&node-id=295%3A5783&mode=design&t=8p5W92IeIyengbhJ-1

**Comment by larssondenise** [comment]
Closing as a duplicate/fold-in to #1720 (Bucket: Notifications v2), which is the active home for this scope. Added the detailed settings-restructure scope there (this was the most complete of the 4 epics folded into this bucket) and moved its 2 open sub-issues directly.
