### ISSUE TITLE
Experience for unauthorized users

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/alkemio#1090]
## Description
Especially when Alkemio's usage increases, people will receive urls that point them to things they don't have access to. For example:
- A member of a private space shares an interesting post to someone outside of the platform
- An admin of a Challenge shares this Challenge which is part of a private Space with people s/he thinks might be interested in this Challenge
- etc.

Reasons for not being authorized to see the content can be that a user **needs to be a member of a journey** to see its content, **or** simply has to **sign in** to see the content. 

Currently, users usually see a **404-page** in the examples above. 
As a more positive example of how this could work, on the contributors page we do have something designed for unauthorized (unauthenticated) users: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdmo4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6c716c1ab40bba6f5a5eb7e54f7dcda17410754f/image.png)

## Initiative / goal
We want to make the experience of new users a **great** experience, which getting a 404-page clearly isn't...

## Acceptance criteria and must have scope
- [ ] Gap analysis
- [ ] UX design for each gap
- [ ] Implementation of designs
- [ ] TBD: Warning/helper text in the share dialog to alert people that this content is restricted to members????

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by techsmyth** [comment]
@SimoneZaza can you please fill in the details of this epic?

**Comment by SimoneZaza** [comment]
@techsmyth ☑️

**Comment by techsmyth** [comment]
Thanks @SimoneZaza

**Comment by larssondenise** [comment]
Closing as a duplicate/superset match with #1528 (Sharing/Collaborating with unauthenticated users 2.0). Note: #1528's current scope is whiteboard-specific, while this epic's ask (and its 7 moved sub-issues) is broader — flagged in the comment so it doesn't get silently narrowed.
