### ISSUE TITLE
Journey settings: challenge, community membership policy

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/alkemio#1168]
## Description
Although an admin can do _way_ more on the platform than ~ a year ago, the settings tab is still sort of the same. New settings were added within the tabs and we added a few tabs since then, but a proper update of the settings page hasn't been done for a long time. This caused the settings page to be a bit unstructured and difficult to navigate, making it harder for (new) admins to shape their journey pages as they seem fit.

## Initiative / goal
Updating the admin settings will ease the flow of setting up a Journey, improving the early experience for new admins with the platfom. 

### Hypothesis
Simplifying the admin of spaces / challenges makes for more usage

## Acceptance criteria and must have scope
- [ ] Challenge: Simplified settings, especially re public / private
- [ ] Add notion of CommunityMembership policy, moving away from multiple preferences (simplify)
- [ ] Remove preferences where possible

## Stakeholders
Support team

## Timeline
tbd

## Design

Figma file:
https://www.figma.com/file/t3XQACWEsDa3r8YPyihmsp/Settings---refresh-Q2%2F3-2023?type=design&node-id=0%3A1&t=xgrnA3AifjMFwzDK-1

**Comment by larssondenise** [comment]
Closing as superseded by #1897 (Settings improvements), whose scope already explicitly includes the Membership Policy consolidation and Visibility/Allowed Actions redesign this asked for. Its 3 open sub-issues have also been closed as superseded.
