### ISSUE TITLE
My Dashboard: live

### ISSUE THREAD

**Issue by SimoneZaza** [alkem-io/alkemio#1211]
## Description

As a frequent user of the platform, I keep my Dashboard open to keep track of new activity in my Spaces. Although this works great every time I refresh the page, I do not want to refresh the page every 5 minutes... 😉

## Acceptance criteria
When there is new activity, directly upload it on My Dashboard. This holds for the:
- [ ] New Memberships block
- [ ] Journey list
- [ ] My Recent Contributions block
- [ ] Recent Contributions from my Spaces block

## Additional Context

Screen shots / UX designs / data that are relevant.

**Comment by larssondenise** [comment]
Closing as a duplicate of #1192 (UX: Subscriptions on all Space pages). Its 1 open sub-issue has been moved there directly.
