### ISSUE TITLE
Possibility to hide the Opportunity tab

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/alkemio#1229]
## Description

As a user I want a simple design for my Challenge when I am not using Opportunities 

## Acceptance criteria

- [ ] Option to hide the opportunity tab in extra block in Challenge Settings > Settings (ON by default)
- [ ] Hide opportunity tab when flag is turned off
- [ ] Hide opportunities block on dashboard when flag is turned off
- [ ] URLs of (if added) opportunities are still accessible + also Opportunities settings tab
- [ ] This is an admin setting, and the opportunities tab will then not be shown to everyone
- [ ] Notification for when the opportunities are hidden or shown again, to all challenge members
- [ ] New preference added for this notification
- [ ] API test for the notifications

## Additional Context
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/d0ea2fe8-c73a-4d07-8398-9cb34a5989bb)

**Comment by larssondenise** [comment]
migration, testing, 4 repositories,

**Comment by larssondenise** [comment]
Closing as obsolete: predicated on the old Hub/Challenge/Opportunity 3-tier model with a dedicated 'Opportunity tab'. Opportunities no longer exist as a distinct entity type in the unified Space/Subspace architecture.
