### ISSUE TITLE
Injection of business logic

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/alkemio#135]
## Description
As host organisation deploying a Cherrytwist instance, I want to be able to inject custom business logic into the operation of the server so that I can add my own business rules into the events on the server

## Acceptance criteria

- [ ] Design for how business logic can be injected into the server
- [ ] Simple prototype demonstrating injected business logic
- [ ] Demo.Simple updated to show the injection of buiness logic
