### ISSUE TITLE
Consistency in notifications for interaction in a space

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/alkemio#1439]
## Description
Currently we have the option to notify the community, but there is inconsistency in how/where it is possible
Shown vs not shown, shown in the dialog vs in a separate dialog

## Goal
Creating consistency in notifying the community

## Hypothesis
A user wants to control whether or not to notify the community

## Must have scope
Client
- [ ] Notify community option in Create Dialog for collaboration tools
- [ ] Notify option for contributions
- [ ] Notify option for events (= contribution?)
- [ ] Notify option for creating a new subspace

Notifications
- [ ] Update set of notifications

## Stakeholders
community

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by larssondenise** [comment]
Closing as a duplicate/fold-in to #1720 (Bucket: Notifications v2). Added its scope there and moved its 2 open sub-issues directly.
