### ISSUE TITLE
Onboarding new Space members - after sign-up flow

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/alkemio#1444]
## Description
After a user signs up to the platform (whether it went easy via LinkedIn/Microsoft authentication or more difficult via email), it is still not always easy to find the Space/get to work

## Goal
Analyse the blockers and small ux fixes we can make to smoothen this experience

## Hypothesis
After the sign-up flow, users are still experiencing difficulties with entering the Space

## Must have scope

- [ ] Clear join / apply button in the about dialog
- [ ] Remove references if there are none
- [ ] Remove info icon, or remove / move the message icon and text
- [ ] If I am invited, I don't want to see the message 'if you want to join, click here to apply'
- [ ] The here should be underscored to highlight that you can click it
- [ ] What can we do with the with Space when there is no content?
- [ ] when no application required: apply or join?
- [ ] Invitation only: nicer message? to say not open for applications, but you can always contact the host?

## Stakeholders
New Space members

## Current interface:
Invited
<img width="1244" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVU2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad15947e94e5d7eeafe4dba76930f3b25f4ec77d/image.png" alt="image.png" />

Apply
<img width="1238" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVk2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c49d0281a682c58e96a8a754c0733b023c378a66/image.png" alt="image.png" />

No application required
<img width="1246" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWc2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9be0ade2c5a6fc670bc311dd96421253bcc82b3c/image.png" alt="image.png" />

Invitation only
<img width="1248" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWs2Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--03cbd5d02f59f126b75fa0a3e8a6e13856e8dbc2/image.png" alt="image.png" />

**Comment by larssondenise** [comment]
Closing as a duplicate/fold-in to #1767 (UI/UX Bucket - Onboarding Flows). Added the detailed UX fix list there and moved its 7 open sub-issues directly.
