### ISSUE TITLE
Bucket: 3rd party issues

### ISSUE THREAD

**Issue by valentinyanakiev** [alkem-io/alkemio#220]
3rd party issues blocking our development.

- [ ] https://github.com/AzureAD/passport-azure-ad/issues/521
- [ ] Unable to reset AAD password through MS Graph
- [ ] 

## Excalidraw
- [ ] Selecting part of content selects the full

**Comment by larssondenise** [comment]
Closing as obsolete: tracks passport-azure-ad/AAD-specific blockers. Auth has since moved toward Ory/OIDC convergence (see active #1812, #1868), so this Azure-AD-specific bucket no longer applies.
