### ISSUE TITLE
User data visibility + control

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/alkemio#265]
Governance: As a user I want control over who can see what aspects of my data

## Acceptance criteria
- [ ] Add preferences section to a user profile
- [ ] Add a privacy section to the preferences
- [ ] Under privacy, allow the user to control who can see what data. Options to provide below.

## User privacy preferences options
- Profile visible to anonymous users (i.e. world visible)
- Profile visible to logged in users
- Display contact information  (email, phone number, name) in my profile 

TBD: review of what other platforms offer in terms of privacy options

**Comment by larssondenise** [comment]
Closing as a duplicate — consolidated into #1041, which covers the same user-data-visibility-and-control scope in more depth (stakeholders, hypothesis, design).
