### ISSUE TITLE
ESSIF: Authorization v2 + eSSIF

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/alkemio#312]
As an architect, I want to be able to manage authorizations on the platform.

## Acceptance criteria
- [ ] Evaluate more powerful resource descriptions
- [ ] Authorization framework to be able to run without any entities from domain model (esp auth policy, but also credentials)
- [ ] Credentials Types to be entities in the domain model, with associated meta data 
- [ ] Design for more flexibility in management / update of authorization policies (avoid all the resetting as currently happens)
- [ ] How the clients get effectively the list of privileges a particular has in a given context
- [ ] ...

## Context
Options for authorization policy specification
- [ ] SimpleGrantLanguage (SGL) for the definition of authorizations. 
- [ ] Evaluate CSAL and how that can be integrated with NestJS / Rules engine such as https://www.npmjs.com/package/json-rules-engine
- [ ] Evaluate looking at credential query language, as is used in Jolocom SDK

https://gitlab.grnet.gr/essif-lab/business/policyman - tip from Rieks

Additional sources:
- https://en.wikipedia.org/wiki/Object-capability_model
- https://w3c-ccg.github.io/zcap-ld/ + https://github.com/w3c-ccg/zcap-ld + https://github.com/digitalbazaar/zcapld
- https://wiki.trustoverip.org/display/HOME/ACDC+%28Authentic+Chained+Data+Container%29+Task+Force

### Feedback from Valentin:
I am confused by the design. I feel it mixes a paradigm like DDD (Domain-Driven Design) authorization, used in platforms / frameworks such as CBAS. For example, as per CBAS documentation:

```typescript
await cbas.evaluateInvocation(invocation)

const expectedReturnValue = {
  resource: {
    "type": "UBS-backup",
    "backupID": "aaabbbccc",
    "vaultID": "bbbcccfff",
    "locations": ["https://ubs.jolocom.io"]
  },
  privileges: ['update-backup', 'delete-backup', 'read-backup'],
  issuer: 'did:example:ubsServer',
  subject: 'did:example:ubsUser',
  constraints: [{
    dailyUploadLimit: "1024MB",
  }]
}
```

The privileges are defined as update-backup, delete-backup etc, and the subject (the actor in our case) is the user (user-agent in our case). This approach is DDD as the authorization is on the level of the domain (user) that can do a specific action (e.g. update-backup) and doesn't follow our largely CRUD model.

We, on the other hand, have largely used a more orthodox CRUD-based credential-based authorization, where policies are based on, largely, resource ID (or lack of it) and a set of predefined operations, largely applicable to the entities we have.

An approach somewhere in between is the AWS approach, where a policy looks like:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInternetGateways",
                "ec2:DescribeAddresses",
                "ec2:DescribeAccountAttributes"
            ],
            "Resource": "*"
        }
    ]
}
```

Here there is a generic framework that can accommodate both DDD and CRUD approach, as Users can be part of User Groups, and Users / UserGroups can have roles consisting of multiple Policies, as the one defined above.

The design flaw, in my opinion, is that we end up with a mixed approach that's hard to comprehend and/or follow and will lead to many edge cases (e.g. Policy vs Credential, in our terminology, which trumps what, where, and why). Requires a discussion on what our desired state looks like.

**Comment by larssondenise** [comment]
Closing as part of the 2021–22 eSSIF Lab self-sovereign-identity research track (see also #455, #272, #547, #569). This exploratory work was never carried into an active epic and the initiative was discontinued — closing as stale/not planned rather than leaving it to linger in the backlog.
