### ISSUE TITLE
Space creation + lifecycle

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/alkemio#363]
## Description
As a platform user I want to know how to create and manage a Space
As an organization owner (verified), I want to be able to request a new Space

## Acceptance criteria
- [ ] User that is an Organization Owner of a verified organization is able to request a new Space
- [ ] Space creation process has multiple states, and requires manual review / approval
- [ ] Org owner receives notifications
- [ ] ...

## Additional Context

Legal commitment:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/785aed32-bea8-41d8-9d89-c49783d22734)

## To discuss
- [ ] How can users create personal Spaces?
- [ ] How does an organisation create a Space?
- [ ] Account mgmt / billing in the context of a subscription?
- [ ] What happens to a Space if subscription ends?
- [ ] Who controls an organisation?

**Comment by larssondenise** [comment]
Terminology update: rewritten from "Challenge Hub" / "ecoverse" language to the current Space model throughout. No change to scope.
