### ISSUE TITLE
eSSIF: Productization + roadmap

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/alkemio#569]
## Description
The functionality demonstrated for eSSIF Lab phase 2 illustrates the power available from using SSI. This needs to be productized. 

## Acceptance criteria and must have scope
- [ ] Robust handling of SSI identities during platform ramp up, including not blocking if not available
- [ ] Caching of SSI information
- [ ] Interaction flows cached across multiple containers
- [ ] Alkemio platform identity that is used to issue Alkemio credentials
- [ ] Hub identity used to issue community credentials
- [ ] ...

**Comment by larssondenise** [comment]
Closing as part of the 2021–22 eSSIF Lab self-sovereign-identity research track (see also #312, #455, #272, #547). This exploratory work was never carried into an active epic and the initiative was discontinued — closing as stale/not planned.
