### ISSUE TITLE
Customize interactions with Space members

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/alkemio#615]
## Description
As a hub community manager, I want to be able to customize the communications that are sent, particularly for new Hub members. 

## Acceptance criteria

- [ ] Ability to edit the contents of the welcome email that is sent to new Hub members 

Plus
- [ ] Notification sent to users on becoming associated with an Organization
- [ ] Ability to edit the contents of the welcome email that is sent to new Organization associates

## Additional Context
The ability to also send notification emails to new Organization associates would allow the automatic triggering of an email to new members of an org that sign up where that organization is setup to match the domain.

Requested by: UWV.

**Comment by makjose** [comment]
Thanks Neil for adding this!

**Comment by larssondenise** [comment]
Closing as a duplicate/fold-in to #1720 (Bucket: Notifications v2), which is the active home for notification-related work. Added its scope as concrete content there since the bucket was empty.
