### ISSUE TITLE
Conversion of entity types

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/alkemio#720]
## Description
As a user I would like to have the option to create one type of entity from another

### Hypothesis
By making it easier to "promote" aspects to Opportunity (and others) the power users are more effective

## Acceptance criteria and must have scope
- [ ] UX design for how users convert from an aspect on a Challenge to an opportunity
- [ ] Mutation to create an opportunity from an aspect
- [ ] Mutation to create a challenge from an aspect

## Stakeholders
VNG
UWV

## Timeline
Before Sept 1st

**Comment by larssondenise** [comment]
Closing as a duplicate of #1489 (Space tidy-up: moving content between Spaces). The old terminology (Aspect/Opportunity) is dead but the concept is covered by the promote/demote scope here.
