### ISSUE TITLE
Bucket: Callouts

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/alkemio#758]
## Description
Next phase for Callouts - likely to be split into multiple epics.

## Initiative / goal
User engagement

### Hypothesis
Admins want to restrict the set of information they are calling out for

## Acceptance criteria and must have scope

Potential items to include?
- [ ] Allowing more fine grained control over who can edit a callout?
- [ ] Optionsto restrict the types of callouts that users can add
- [ ] Different display options for key callouts (e.g. cards as per TIPs feedback)
- [ ] ...

InnovationFlow:
- [ ] Expand button for list of callouts in Challenge
- [ ] something to ensure the tags take less space
- [ ] Easily edit challenge / opportunity flow / add steps
- [ ] Description box to be adjustable
- [ ] Description box per phase
- [ ] Next step / previous step
- [ ] Dialog to move callouts to other tabs to also be drag and drop 

- [ ] Subscriptions for callout related events
- [ ] Ordering of callouts via admin 
- [ ] Interactions around the different Callout states, e.g. when to archive? Timelines / dates?

There is so much more potential for these Callouts that we want to explore with you in the coming months. For example:
- <b>Additional Callout types</b>: for example to let the members <i>vote</i>, or in <i>task list</i> with jobs to be done
- <b>Enriching the Callout concept</b>: for example <i>closing</i> your Callout for further answers, <i>timeline</i> for the Callout (when it is open, when it is closed etc), <i>summarizing</i> the results, or <i>connecting</i> your Callouts to different Innovation Flow fases.

## Stakeholders
UWV

## Timeline
tbd

**Comment by larssondenise** [comment]
Closing — folded as additional context into #1998 (Posts extensions), see comment there. Most of this bucket's remaining ideas are admin/InnovationFlow controls rather than Post content extensions; re-file individually if still wanted.
