### ISSUE TITLE
Classifications of content via tagsets

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/alkemio#776]
## Description
Allowing classifications to be applied to content on the platform

A classification tagset would be a set of tags that can be chosen from, either 1 or many. An example would be the SDGs.

## Initiative / goal
Engaging users by allowing them to find relevant content

### Hypothesis
By making it easier to classify content it becomes easier for users to engage

## Acceptance criteria and must have scope
- [ ] Ability to manage classification tagsets as e.g. part of TemplatesSet
- [ ] Having both global and per hub classification tagsets
- [ ] Add notion of a classification tagset that can be managed per hub, with a name and a set of allowed values
- [ ] Design for how the interaction with a classification tagset happens
- [ ] Specification for where the classification tagset would be used e.g. per challenge, per aspect, ...

## Stakeholders
UWV wanted it as a way to classify all activity according to their strategic goals
This is something that UWV would like for assigning their strategic priorities to all the entities. 
Also came up from Digicampus, and SZW. 
## Timeline
tbd

## Additional Context

One option would be to simply have a list of allowed values for tagsets on the relevant entities. Or to have two tagsets, one free form and one for the classification tagset.

**Comment by larssondenise** [comment]
Closing as a duplicate of #[2077](https://github.com/alkem-io/alkemio/issues/2077) (Classifications follow up), which ships the Classification Template system this asked for, scoped to Spaces this iteration. Its open sub-issues have been moved there directly.
