### ISSUE TITLE
Knowledge: Suggested best practice templates

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/alkemio#785]
## Description
Facilitate the suggestion and approval process for best practice templates

## Initiative / goal
Best Practices sharing of templates

### Hypothesis
Users are able to exchange best practices in (easy manner?).

## Acceptance criteria and must have scope
_Define what is a must-have for launch and in-scope. Keep this section fluid and dynamic until you lock-in priority during planning._

1. Hub/Setting/Templates
- [x] Hub admins are able to suggest templates from within their Hub to be published by their (facilitating) organization

2. Organization/Settings/Templates
- [x] Org admins are able to publish templates that are suggested by a Hub admin from a Hub facilitated by this Organization

3. Notifications emails to
- [ ] Org admins when a new template has been suggested by a Hub admin
- [ ] Hub admins when their suggestion has been approved/declined

4. User preferences
- [ ] Receive notification when a template has been suggested by a Hub admin (Organization administration)
- [ ] Receive notification when a template that you suggested has been approved/rejected (Community administration)

## Stakeholders
- Alkemio Steward
- UWV
- Development Team
- Product team

## Timeline
- UI Designs 
- Development capacity
- Approval from CTO

## Miro board
https://miro.com/app/board/uXjVOkjWSVI=

Platform template management:
https://xd.adobe.com/view/d4b6bc7f-ea02-4473-9c52-8ce59e60651c-81e5/

July 2022 Figma file: https://www.figma.com/file/PwLYdTm1PNEZvPMpZt94up/Platform-Template-Library?node-id=0%3A1

Potential design:

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/d62176a7-1371-4904-b1e9-dba08e368268)

**Comment by larssondenise** [comment]
Closing as a duplicate/fold-in to #1734 (Templates: library UX). Added the suggest-and-approve governance workflow as missing scope there.
