### ISSUE TITLE
Innovation Flow: Definition to include goal/checklist/callouts

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/alkemio#836]
## Description
The innovation flow is currently not an appealing feature and not really guiding people through the different stages of a challenge or opportunity as it remains unclear when the next step should be taken and what happens then. 

## Initiative / goal
To make the innovation flow an attractive and powerful feature on the platform, we need to make it more useful/appealing

### Hypothesis
By adding checklists and goals to each stage and updating the type of innovation flows that users can choose, they will be more interesting

## Acceptance criteria and must have scope
- [ ] Innovation flow to include stages with a goal and checklist to move on to the next stage
- [ ] Use the stately components
- [ ] Next stage triggers set of callouts
- [ ] Callout templates
- [ ] Admin side to manage the innovation flow 

## Stakeholders
UWV?
Digicampus?

## Timeline
?

## Additional context
![Schermafbeelding 2022-10-17 om 17.11.42.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/d6bcccc1-9e86-4a10-ab44-4e5094be3caa)
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/b2fea59d-bd07-456c-b6ef-d674cfe779f1)

**Comment by larssondenise** [comment]
Closing as a duplicate of #1570 (Innovation Flow: settings and default callout content). Added the checklist/goal stage-gating concept there and moved its 1 open sub-issue directly.
