### ISSUE TITLE
Space Visualization component

### ISSUE THREAD

**Issue by larssondenise** [alkem-io/alkemio#840]
## Description
Each user that lands in the Hub wants to know where they are. It is possible to navigate back from the opportunity to the challenge or hub above, but not the other way around. It is for some users unclear where they are. For example also thinking that explore on opportunity dashboard will bring you back to explore of Hub. 

## Initiative / goal
Create an overview in a visualized structured tree/other visualization of the Hub and the containing Challenges and Opportunities.

### Hypothesis
This visualization helps people to navigate to the content they want to contribute to or search for (for example if it is a opportunity deep down)

## Acceptance criteria and must have scope
- [ ] D3 related visualizations into a separate package  + reusable across clients
- [ ] Visual component for Innovation Flows, replacing current D3 related code in the client-web
- [ ] Ability to see the amount of challenges and opportunities underneath on the dashboard of the Hub?
- [ ] Ability to navigate through the structure

## Stakeholders
VNG & PZH

**Comment by larssondenise** [comment]
discuss overlap/split with #649
