### ISSUE TITLE
Membership models

### ISSUE THREAD

**Issue by techsmyth** [alkem-io/alkemio#935]
## Description
Ensuring that it is clear to all users what membership implies and what restrictions apply when leaving a community

## Initiative / goal
Engagement

### Hypothesis
Clarity on membership models will reduce edge cases

## Acceptance criteria and must have scope
- [ ] A user cannot remove his membership if still a lead
- [ ] A user cannot remove membership of a Hub if a member of a child challenge / opportunity (and same on opportunity)
- [ ] A user is able to remove his lead role

## Stakeholders
Developers, community

## Timeline
tbd

## Design
Also impacted by contributor visibility epic

**Comment by larssondenise** [comment]
Closing as a duplicate of #1179 (Roles: Flexible & Templatable community roles). Added the specific leave/removal edge-case rules as context there.
